In [1]:
import requests as rq
import pandas as pd
from bs4 import BeautifulSoup as bs
import numpy as np

In [5]:
df = pd.read_csv("DataFrame.csv")
df1 = pd.read_csv("DataFrame1000-1248.csv")
df2 = pd.read_csv("DataFrame1250-1499.csv")
df3 = pd.read_csv("DataFrame1500-1749.csv")
df4 = pd.read_csv("DataFrame1750-1999.csv")
df5 = pd.read_csv("DataFrame2000-2249.csv")
df6 = pd.read_csv("DataFrame2250-2499.csv")
df7 = pd.read_csv("DataFrame2500-2749.csv")
df8 = pd.read_csv("DataFrame2750-2999.csv")
df9 = pd.read_csv("DataFrame3000-3249.csv")
df10 = pd.read_csv("DataFrame3250-3499.csv")
df11 = pd.read_csv("DataFrame3500-3749.csv")
df12 = pd.read_csv("DataFrame3750-3999.csv")
df13 = pd.read_csv("DataFrame4000-4249.csv")
df14 = pd.read_csv("DataFrame4250-4499.csv")
df15 = pd.read_csv("DataFrame4500-4749.csv")
df16 = pd.read_csv("DataFrame4750-4999.csv")
df17 = pd.read_csv("DataFrame5000-5248.csv")
df18 = pd.read_csv("DataFrame5250-5499.csv")
df19 = pd.read_csv("DataFrame5500-5748.csv")
df20 = pd.read_csv("DataFrame5750-5999.csv")
df21 = pd.read_csv("DataFrame6000-6249.csv")
df22 = pd.read_csv("DataFrame6250-6499.csv")
df23 = pd.read_csv("DataFrame6500-6748.csv")
df24 = pd.read_csv("DataFrame6750-6999.csv")
df25 = pd.read_csv("DataFrame7000-7249.csv")
df26 = pd.read_csv("DataFrame7250-7499.csv")
df27 = pd.read_csv("DataFrame7500-7749.csv")
df28 = pd.read_csv("DataFrame8000-8249.csv")
df29 = pd.read_csv("DataFrame8250-8498.csv")
df30 = pd.read_csv("DataFrame8500-8749.csv")
df31 = pd.read_csv("DataFrame8750-8999.csv")
df32 = pd.read_csv("DataFrame9000-9249.csv")
df33 = pd.read_csv("DataFrame9250-9499.csv")

DFlist = [df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,
         df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,
         df21,df22,df23,df24,df25,df26,df27,df28,df29,df30,
         df31,df32,df33]

should = df.shape[0]

for dfi in DFlist:
    df = df.append(dfi)
    should = should + dfi.shape[0]

C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)
C:\Users\matan\AppData\Local\Temp\ipykernel_34352\3391283268.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dfi)

In [6]:
should

440692

In [7]:
df.shape[0]

440692

In [8]:
df.to_csv("TotalDataFrame.csv", encoding="utf-8-sig")

In [9]:
Major = pd.read_csv("TotalDataFrame.csv")

In [11]:
Major.drop(columns = ["Unnamed: 0","Unnamed: 0.1"], inplace = True)

In [12]:
Major

,date,city,address,rooms,space,floor,price,price_per_sqm,build_year,apartment,prop_type,parking,yard
0,28/01/2021,ירושלים,רמת מוצא 27,5.0,134.0,1.0,"3,675,000","27,425",2000.0,1,קוטג' חד משפחתי,1 רכבים,152.0
1,28/01/2021,גבעתיים,המבוא 9,2.0,72.0,3.0,"1,961,800","27,247",1960.0,7,דירה בבית קומות,0 רכבים,NaN
2,28/01/2021,ירושלים,רמת מוצא 27,5.0,134.0,NaN,"3,675,000","27,425",2000.0,NaN,קוטג' חד משפחתי,NaN,NaN
3,28/01/2021,גבעתיים,המרי 26,2.0,72.0,NaN,"1,961,800","27,247",1960.0,NaN,דירה בבית קומות,NaN,NaN
4,27/01/2021,אור עקיבא,אור עקיבא 3,5.0,120.0,8.0,"1,665,000","13,875",2017.0,39,דירה בבית קומות,2 רכבים,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
440687,02/7/2015,ראשון לציון,הירשפלד 11,4.0,87.0,2.0,"1,500,000","17,241",1974.0,NaN,דירה בבית קומות,NaN,NaN
440688,02/7/2015,אשקלון,פקיעין 6,4.0,113.0,4.0,"1,100,000","9,734",1998.0,41,דירה בבית קומות,NaN,NaN
440689,02/7/2015,אשקלון,מגידו 8,4.0,78.0,2.0,"960,000","12,307",2002.0,8,דירה בבית קומות,NaN,NaN
440690,02/7/2015,אשדוד,שפירא אברהם 5,3.0,61.0,4.0,"810,000","13,278",1971.0,16,דירה בבית קומות,NaN,NaN
440691,02/7/2015,רחובות,מקס שיין 13,4.0,99.0,5.0,"1,500,000","15,151",2008.0,19,דירה בבית קומות,2 רכבים,NaN